### PR TITLE
Notebook containing the HOD analysis of DC2

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This PR addresses #41 and adds a notebook querying cosmoDC2 and computing the HOD.

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
This is the HOD for galaxies with z < 1.5 and i < 24.5

image

**Comment by damonge** [comment]
By eye I'd say the slope of N_sat(M_h) is around 1. @fjaviersanchez can you check if this is more or less accurate?

**Comment by fjaviersanchez** [comment]
Yes, a quick fit of the first bin gives me 1.31 (including all the points) and 0.93 if I start the fit at Mh ~ 1E12.5

**Comment by damonge** [comment]
OK, yeah, the latter is the one we want. Great!

**Comment by egawiser** [comment]
I gather that the plateau in centrals is at 10^0 i.e. 1 per halo.  It took me a while to realize that given the particular axis labels - we should make sure for any plots we show publicly that 1 (or 10^0) is a labeled tickmark.

**Comment by fjaviersanchez** [comment]
Fixed! Thanks for the feedback

image

**Comment by fjaviersanchez** [comment]
@damonge Do you have any suggestions for reviewers or should I merge this?

**Comment by damonge** [comment]
Merge!

**Pull request merged**
